version: '3'

services:
  chat-system:
    image: buixuankhai1204/chat-system:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend
networks:
  backend:
    external: true